language: clojure
lein: lein
script: lein do clean, javac, test :all, doo phantom test once


# Cache our Maven deps to be kind to clojars, github, docker images
cache:
    directories:
    - $HOME/bin
    - $HOME/.m2
jdk:
    # https://github.com/travis-ci/travis-ci/issues/5227
    - openjdk7
    - oraclejdk7
    - oraclejdk8

before_install:
    # ES5 needs this
    - sudo sysctl -w vm.max_map_count=262144
    # create log & bin dir if missing
    - mkdir -p $LOG_DIR
    - mkdir -p $BIN_DIR

    #https://github.com/travis-ci/travis-ci/issues/5227
    - echo "127.0.0.1 "`hostname` | sudo tee /etc/hosts

    # install docker-compose if not in cache
    - if [ ! -f $COMPOSE_BIN ]; then curl -L {$COMPOSE_URI}/docker-compose-`uname -s`-`uname -m` > $COMPOSE_BIN; fi
    - chmod +x $COMPOSE_BIN 

before_script:
    - $COMPOSE_BIN -f containers/dev/docker-compose.yml up -d> $COMPOSE_LOG
    # Wait ES
    - until curl http://127.0.0.1:9200/; do sleep 1; done

services:
    - docker 

env:
    global:
      - JAVA_OPTS="-XX:MaxPermSize=256m"
      - LOG_DIR=$HOME/log
      - BIN_DIR=$HOME/bin
      - COMPOSE_URI=https://github.com/docker/compose/releases/download/1.9.0
      - COMPOSE_BIN=$HOME/bin/docker-compose-1-9-0
      - COMPOSE_LOG=$HOME/log/docker-compose.log
